server:
  port: 80
  servlet:
    context-path: /authentication

spring:
  application:
    name: authentication
  data:
    rest:
      default-media-type: application/json
  jpa:
    open-in-view: false

management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: false
  endpoints:
    web:
      discovery:
        enabled: false
    enabled-by-default: false

springdoc:
  api-docs:
    path: /api-docs

logging:
  config: src/main/resources/logback.xml
  level:
    org.springframework.web: INFO
    com.code.challenge.authentication: INFO

app:
  fixtures:
    enabled: true
  mail:
    debug: false
    from: authentication@service.local
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    transport:
      protocol: smtp
      smtp:
        auth: true
        starttls:
          enable: true
