server:
  port: 80
  servlet:
    context-path: /authentication

spring:
  application:
    name: authentication
  data:
    rest:
      default-media-type: application/json

management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: false
  endpoints:
    web:
      discovery:
        enabled: false
    enabled-by-default: false

springdoc:
  api-docs:
    path: /api-docs

logging:
  config: src/main/resources/logback.xml
