# --- docker compose
up:
	@echo "Up in progress..."
	docker-compose up -d
	@echo "Done!"

build:
	@echo "Build in progress..."
	docker-compose down
	docker-compose create
	@echo "Done!"

stop:
	@echo "Stop in progress..."
	docker-compose down
	@echo "Done!"
